version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/myportfolio
    depends_on:
      - db
    
  db:
    image: postgres
    restart: always
    env_file:
      - .env